name: release
on: 
    push:
        tags:
        - '*'

jobs:
  build:
    name: release
    runs-on: ubuntu-18.04
    steps:
        - name: fetch
          uses: actions/checkout@v1
        - name: build
          run: |
              echo $GITHUB_SHA
              python3 host_actions.py `git describe`
              ln -s wheelhouse dist
        - name: Publish package
          uses: pypa/gh-action-pypi-publish@master
          with:
            user: __token__
            password: ${{ secrets.pypi_password }}
